# Generated by Django 2.2.9 on 2022-05-21 01:35

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220521_1133'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='dont_follow_self',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='dont_follow_self'),
        ),
    ]
